# Generated by Django 4.1.4 on 2022-12-22 13:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Diagnosticos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_diagnostico', models.CharField(max_length=150, verbose_name='Tipo de diagnóstico')),
                ('tratamientos', models.CharField(max_length=150, verbose_name='Tratamientos')),
            ],
        ),
        migrations.CreateModel(
            name='Dueno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dni', models.IntegerField(verbose_name='DNI')),
            ],
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricula', models.CharField(max_length=8, verbose_name='Matrícula')),
            ],
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_animal', models.CharField(
                    choices=[(1, 'Perro'), (2, 'Gato'), (3, 'Pájaro'), (4, 'Pez'), (5, 'Vaca'), (6, 'Caballo'),
                             (7, 'Oveja'), (8, 'Cabra'), (9, 'Cerdo')], default='Perro', max_length=10,
                    verbose_name='Tipo de animal')),
                ('raza', models.CharField(max_length=150, verbose_name='Raza')),
                ('nombre_paciente', models.CharField(max_length=150, null=True, verbose_name='Nombre')),
                ('edad', models.DateField(blank=True, null='True', verbose_name='Fecha de nacimiento')),
                ('color', models.CharField(blank=True, max_length=100, verbose_name='Color de tu mascota')),
            ],
            options={
                'ordering': ['tipo_animal'],
            },
        ),
        migrations.CreateModel(
            name='Registro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('pass_word', models.CharField(max_length=20, verbose_name='Contraseña')),
            ],
        ),
        migrations.CreateModel(
            name='Vacunas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cant_vacunas', models.CharField(max_length=150, verbose_name='Vacunas aplicadas')),
                ('prox_vacunas', models.CharField(max_length=150, verbose_name='Proximas vacunas a aplicar')),
            ],
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, verbose_name='Nombre/s')),
                ('apellido', models.CharField(max_length=150, verbose_name='Apellido/s')),
                ('direccion', models.CharField(max_length=150, verbose_name='Dirección')),
                ('telefono', models.IntegerField(verbose_name='Teléfono')),
                ('num_dni', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='base.dueno')),
                ('num_matricula', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='base.empleado')),
            ],
        ),
    ]
