# Generated by Django 4.1.4 on 2022-12-29 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_rename_nombre_paciente_paciente_nombre_animal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dueno',
            name='dni',
        ),
        migrations.AddField(
            model_name='dueno',
            name='localidad',
            field=models.CharField(max_length=150, null=True, verbose_name='Localidad'),
        ),
    ]
