# Generated by Django 4.1.4 on 2022-12-31 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_alter_persona_num_dni_alter_persona_num_matricula'),
    ]

    operations = [
        migrations.AddField(
            model_name='dueno',
            name='num_ident',
            field=models.BigIntegerField(null=True, verbose_name='Documento'),
        ),
    ]
